swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
host: localhost:3001
basePath: /api/v1
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /user/transactions:
    get:
      summary: Get all transactions for the current month
      responses:
        '200':
          description: Successful request
        '401':
          description: The provided JWT token is missing or invalid
        '404':
          description: Transaction not found
      security:
        - Bearer: []
  /user/transactions/{transactionId}:
    get:
      summary: Get the details of a specific transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction
      responses:
        '200':
          description: Successful request
        '401':
          description: The provided JWT token is missing or invalid
        '404':
          description: Transaction not found
      security:
        - Bearer: []
    post:
      summary: Add information about a specific transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              infoToAdd:
                type: string
            description: The information to add
      responses:
        '200':
          description: Successful request
        '401':
          description: The provided JWT token is missing or invalid
        '404':
          description: Transaction not found
      security:
        - Bearer: []
    put:
      summary: Editing information relating to a specific transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              infoToModify:
                type: string
            description: The information to modify
      responses:
        '200':
          description: Successful request
        '401':
          description: The provided JWT token is missing or invalid
        '404':
          description: Transaction not found
      security:
        - Bearer: []
    delete:
      summary: Delete information from a specific transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              infoToDelete:
                type: string
            description: The information to delete
      responses:
        '200':
          description: Successful request
        '401':
          description: The provided JWT token is missing or invalid
        '404':
          description: Transaction not found
      security:
        - Bearer: []
